# Generated by Django 2.0.5 on 2018-05-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('create_time', models.DateTimeField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('ToDolist', models.TextField()),
                ('memo', models.TextField()),
            ],
        ),
    ]
