# Generated by Django 2.0.5 on 2018-05-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('username', models.CharField(default='', max_length=100, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=30, verbose_name='密码')),
                ('create_time', models.DateTimeField(default=0, verbose_name='用户创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserTodo',
            fields=[
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('ToDolist', models.TextField()),
                ('memo', models.TextField()),
            ],
        ),
    ]
