# Generated by Django 2.0.5 on 2018-05-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='UserId',
            field=models.IntegerField(),
        ),
    ]
