# Generated by Django 2.0.5 on 2018-06-01 07:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertodo',
            name='created_time',
        ),
        migrations.AddField(
            model_name='usertodo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 7, 49, 18, 623084, tzinfo=utc), verbose_name='截至时间'),
        ),
    ]
