# Generated by Django 2.0.5 on 2018-05-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180519_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='UserId',
        ),
    ]
