# Generated by Django 2.0.5 on 2018-06-01 20:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180601_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertodo',
            name='memo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='便签'),
        ),
        migrations.AlterField(
            model_name='usertodo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 1, 20, 27, 54, 114938), verbose_name='截至时间'),
        ),
    ]
