# Generated by Django 2.0.5 on 2018-06-03 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180601_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertodo',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 3, 15, 32, 20, 756344), verbose_name='截至时间'),
        ),
    ]
